import { hexToRgb } from '../color';
import { parsePixelPlan } from '../schema';
import type { DrawOp, PixelPlan } from '../types';

interface LuaOutputPaths {
  asepriteFile: string;
  pngFile: string;
}

export function generateAsepriteLua(planInput: PixelPlan, outputPaths: LuaOutputPaths): string {
  const plan = parsePixelPlan(planInput);
  const layerNames = plan.layers.map((layer) => layer.name);
  const firstLayer = layerNames[0] ?? 'Base';
  const activeLayer = layerNames.includes('Edits') ? 'Edits' : layerNames.includes('Base') ? 'Base' : firstLayer;
  const frameMetas = collectFrameMetas(plan);
  const frameCount = Math.max(...frameMetas.map((frame) => frame.index), 1);
  const lines: string[] = [
    '-- Generated by AsePilot. Do not edit this file unless you know the Aseprite Lua API.',
    'local pc = app.pixelColor',
    `local sprite = Sprite(${plan.canvas.width}, ${plan.canvas.height}, ColorMode.RGB)`,
    `local frameCount = ${frameCount}`,
    'while #sprite.frames < frameCount do',
    '  sprite:newEmptyFrame()',
    'end',
    'local layers = {}',
    'local images = {}',
    'for frameIndex = 1, frameCount do',
    '  images[frameIndex] = {}',
    'end',
    '',
    'local function addLayer(name, index, opacity, visible)',
    '  local layer',
    '  if index == 1 and #sprite.layers >= 1 then',
    '    layer = sprite.layers[1]',
    '  else',
    '    layer = sprite:newLayer()',
    '  end',
    '  layer.name = name',
    '  layer.opacity = opacity',
    '  layer.isVisible = visible',
    '  layer.isEditable = true',
    '  layers[name] = layer',
    'end',
    '',
    'local function ensureImage(frameIndex, layerName)',
    '  if images[frameIndex] == nil then',
    '    images[frameIndex] = {}',
    '  end',
    '  if images[frameIndex][layerName] == nil then',
    `  local image = Image(${plan.canvas.width}, ${plan.canvas.height}, ColorMode.RGB)`,
    '  image:clear()',
    '    images[frameIndex][layerName] = image',
    '  end',
    '  return images[frameIndex][layerName]',
    'end',
    ''
  ];

  for (const frame of frameMetas) {
    if (frame.durationMs) {
      lines.push(`sprite.frames[${frame.index}].duration = ${Number((frame.durationMs / 1000).toFixed(3))}`);
    }
  }

  layerNames.forEach((layerName, index) => {
    const layer = plan.layers[index];
    const opacity = Math.round((layer?.opacity ?? 1) * 255);
    const visible = layer?.visible === false ? 'false' : 'true';
    lines.push(`addLayer(${luaString(layerName)}, ${index + 1}, ${opacity}, ${visible})`);
  });

  lines.push('', 'local colors = {}');
  for (const color of plan.palette) {
    const rgb = hexToRgb(color.hex);
    lines.push(`colors[${luaString(color.hex.toLowerCase())}] = pc.rgba(${rgb.r}, ${rgb.g}, ${rgb.b}, 255)`);
  }

  lines.push(
    '',
    `local currentLayer = ${luaString(firstLayer)}`,
    `local currentFrame = ${frameMetas[0]?.index ?? 1}`,
    '',
    'local function putPixel(frameIndex, layerName, x, y, color)',
    '  local image = ensureImage(frameIndex, layerName)',
    '  local pixel = colors[string.lower(color)]',
    '  if image ~= nil and pixel ~= nil then',
    '    image:drawPixel(x, y, pixel)',
    '  end',
    'end',
    '',
    'local function fillRect(frameIndex, layerName, x, y, width, height, color)',
    '  for yy = y, y + height - 1 do',
    '    for xx = x, x + width - 1 do',
    '      putPixel(frameIndex, layerName, xx, yy, color)',
    '    end',
    '  end',
    'end',
    '',
    'local function drawRect(frameIndex, layerName, x, y, width, height, color)',
    '  fillRect(frameIndex, layerName, x, y, width, 1, color)',
    '  fillRect(frameIndex, layerName, x, y + height - 1, width, 1, color)',
    '  fillRect(frameIndex, layerName, x, y, 1, height, color)',
    '  fillRect(frameIndex, layerName, x + width - 1, y, 1, height, color)',
    'end',
    '',
    'local function drawLine(frameIndex, layerName, x1, y1, x2, y2, color)',
    '  local x = x1',
    '  local y = y1',
    '  local dx = math.abs(x2 - x1)',
    '  local dy = -math.abs(y2 - y1)',
    '  local sx = x1 < x2 and 1 or -1',
    '  local sy = y1 < y2 and 1 or -1',
    '  local err = dx + dy',
    '  while true do',
    '    putPixel(frameIndex, layerName, x, y, color)',
    '    if x == x2 and y == y2 then break end',
    '    local e2 = 2 * err',
    '    if e2 >= dy then',
    '      err = err + dy',
    '      x = x + sx',
    '    end',
    '    if e2 <= dx then',
    '      err = err + dx',
    '      y = y + sy',
    '    end',
    '  end',
    'end',
    '',
    'local function drawEllipse(frameIndex, layerName, x, y, width, height, color, fill)',
    '  local rx = math.max(width / 2, 0.5)',
    '  local ry = math.max(height / 2, 0.5)',
    '  local cx = x + rx - 0.5',
    '  local cy = y + ry - 0.5',
    '  for yy = y, y + height - 1 do',
    '    for xx = x, x + width - 1 do',
    '      local normalized = ((xx - cx) ^ 2) / (rx ^ 2) + ((yy - cy) ^ 2) / (ry ^ 2)',
    '      if (fill and normalized <= 1) or ((not fill) and normalized > 0.72 and normalized <= 1.12) then',
    '        putPixel(frameIndex, layerName, xx, yy, color)',
    '      end',
    '    end',
    '  end',
    'end',
    ''
  );

  for (const op of plan.drawOps) {
    lines.push(renderDrawOpLua(op));
  }

  lines.push('', 'for frameIndex = 1, frameCount do', '  for _, name in ipairs({');
  layerNames.forEach((layerName, index) => {
    const suffix = index === layerNames.length - 1 ? '' : ',';
    lines.push(`    ${luaString(layerName)}${suffix}`);
  });
  lines.push(
    '  }) do',
    '    sprite:newCel(layers[name], frameIndex, ensureImage(frameIndex, name), Point(0, 0))',
    '  end',
    'end',
    '',
    `app.activeSprite = sprite`,
    `app.activeLayer = layers[${luaString(activeLayer)}]`,
    `app.activeFrame = sprite.frames[1]`,
    '',
    `app.command.SaveFileAs { ui=false, filename=${luaString(outputPaths.asepriteFile)} }`,
    `app.command.SaveFileCopyAs { ui=false, filename=${luaString(outputPaths.pngFile)} }`,
    'app.command.CloseFile { ui=false }',
    ''
  );

  return `${lines.join('\n')}\n`;
}

function renderDrawOpLua(op: DrawOp): string {
  switch (op.op) {
    case 'layer':
      return `currentLayer = ${luaString(op.name)}`;
    case 'frame':
      return `currentFrame = ${op.index}`;
    case 'setPixel':
      return `putPixel(currentFrame, ${luaLayer(op)}, ${op.x}, ${op.y}, ${luaString(op.color.toLowerCase())})`;
    case 'fillRect':
      return `fillRect(currentFrame, ${luaLayer(op)}, ${op.x}, ${op.y}, ${op.width}, ${op.height}, ${luaString(op.color.toLowerCase())})`;
    case 'rect':
      return `drawRect(currentFrame, ${luaLayer(op)}, ${op.x}, ${op.y}, ${op.width}, ${op.height}, ${luaString(op.color.toLowerCase())})`;
    case 'line':
      return `drawLine(currentFrame, ${luaLayer(op)}, ${op.x1}, ${op.y1}, ${op.x2}, ${op.y2}, ${luaString(op.color.toLowerCase())})`;
    case 'ellipse':
      return `drawEllipse(currentFrame, ${luaLayer(op)}, ${op.x}, ${op.y}, ${op.width}, ${op.height}, ${luaString(op.color.toLowerCase())}, ${op.fill === true ? 'true' : 'false'})`;
  }
}

function collectFrameMetas(plan: PixelPlan): Array<{ index: number; durationMs?: number }> {
  const frameMap = new Map<number, { index: number; durationMs?: number }>();

  for (const frame of plan.frames ?? []) {
    frameMap.set(frame.index, {
      index: frame.index,
      durationMs: frame.durationMs
    });
  }

  for (const op of plan.drawOps) {
    if (op.op === 'frame' && !frameMap.has(op.index)) {
      frameMap.set(op.index, { index: op.index });
    }
  }

  if (frameMap.size === 0) {
    frameMap.set(1, { index: 1 });
  }

  return [...frameMap.values()].sort((left, right) => left.index - right.index);
}

function luaLayer(op: Extract<DrawOp, { layer?: string }>): string {
  return op.layer ? luaString(op.layer) : 'currentLayer';
}

function luaString(value: string): string {
  return JSON.stringify(value.replaceAll('\\', '/'));
}
